### ISSUE TITLE
Restart does not apply configuration changes

### ISSUE THREAD

**Issue by StarpTech** [platdesign/node-compose#8]
When I change the configuration e.g change the `cmd` or add a `environment` variable the config wont be loaded again.

**Comment by platdesign** [comment]
`restart` only restarts the image-processes. To reload `node-compose.yml` use `reload` ;)

**Comment by StarpTech** [comment]
Nice,  thanks!

**Comment by StarpTech** [comment]
It is possible to reload a specific Image?

**Comment by platdesign** [comment]
No, the whole config file is reloaded and applied to all images. Currently each image will stop, reconfigure and start again. There is a task on my todos to check if the image-config has hanged, to prevent restarting images with untouched configs.
